### ISSUE TITLE
addEventListener with strict type checking

### ISSUE THREAD

**Issue by EricKit** [wsmd/mapkit-typescript#1]
First of all I wanted to say thank you for making this, it's awesome.

In `mapkit.Annotation.d.ts` there is: 

```
* @param listener The callback function to invoke. listener is passed an
* annotation event as its sole argument.

  addEventListener<K extends keyof AnnotationEvents<this>>(
      type: K,
      listener: () => void,
      thisObject?: object,
    ): void;
```

When I pass an object to a listener:
```
  newMarker.addEventListener('select', (event: mapkit.EventBase<mapkit.MarkerAnnotation>) => {
      const myAnnotation = event.target;
      console.log('Clicked');
    });
```
It errors that `(event: ...) => void` is not assignable to `() => void`.

Would it be better to declare the addEventListener as:

```
    addEventListener<K extends keyof AnnotationEvents<this>>(
      type: K,
      listener: (event: mapkit.EventBase<any>) => void,
      thisObject?: object,
    ): void;
```

Of note, I'm sure there is something better than any to put in there.

**Comment by wsmd** [comment]
Thanks for reporting the issue @EricKit! Good catch!

A fix is now being worked on in #2, which is now published under `mapkit-typescript@5.13.2-beta.0`, if you are interested in testing it before I publish `5.13.2`.
